In [3]:
import torch

In [2]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [3]:
t1.shape

torch.Size([2, 2])

In [4]:
t1.size

<function Tensor.size>

In [5]:
t1.size()

torch.Size([2, 2])

In [6]:
t3 = torch.tensor([8,9],[10,11])

TypeError: tensor() takes 1 positional argument but 2 were given

In [7]:
t3 = torch.tensor([[8,9],[10,11]])

In [8]:
t3.shape

torch.Size([2, 2])

In [9]:
torch.cat((t1,t2),dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [10]:
torch.stack((t1,t2),dim=0)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [11]:
t3 = torch.stack((t1,t2),dim=0)

In [12]:
t3.shape

torch.Size([2, 2, 2])

In [13]:
t1.shape

torch.Size([2, 2])

In [14]:
torch.unsqueeze(t1,dim=0)

tensor([[[1, 2],
         [3, 4]]])

In [15]:
t4 = torch.unsqueeze(t1,dim=0)

In [16]:
t4.shape

torch.Size([1, 2, 2])

In [18]:
t5 = torch.unsqueeze(t1,dim=1)

In [19]:
t5.shape

torch.Size([2, 1, 2])

In [20]:
t5

tensor([[[1, 2]],

        [[3, 4]]])

In [21]:
t6 = torch.unsqueeze(t1,dim=2)

In [22]:
t6.shape

torch.Size([2, 2, 1])

In [23]:
t6

tensor([[[1],
         [2]],

        [[3],
         [4]]])

In [6]:
x = torch.tensor([
        [5, 9, 1],
        [3, 2, 8],
        [7, 4, 0]
    ])
c = torch.tensor([
        [0, 0, 0],
        [1, 2, 0],
        [2, 2, 1]
    ])
x.gather(0, c)

tensor([[5, 9, 1],
        [3, 4, 1],
        [7, 4, 8]])